---
- name: extract artifact
  ansible.builtin.unarchive:
    src: files/artifact.tar.gz
    dest: ~/

- name: "install npm"
  become: yes
  apt:
    name: npm
    state: latest

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest

- name: "start the app"
  become: yes
  command: pm2 start npm -- start